project:
  type: website
  output-dir: docs

website:
  title: "Final Project"
  navbar:
    left:
      - text: "PDF Report"
        href: index.pdf
    right:
      - text: "GitHub Repo"
        href: https://github.com/Terrachizoid/JSC370Project

      - text: "Video"
        href: https://drive.google.com/file/d/14tzBphUTKrdICVjE05h2JedrccX630y7/view?usp=drive_link

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    embed-resources: false