project:
  type: website
  output-dir: docs

website:
  title: "Final Project"
  navbar:
    left:
      - text: "PDF Report"
        href: docs/index.pdf
    right:
      - text: "GitHub Repo"
        href: https://github.com/Terrachizoid/JSC370Project

      - text: "Video"
        href: https://your-video-link

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    embed-resources: false